### PR TITLE
Fix #38 add support for IDA v7.0

### LINKED ISSUE #38: IDA 7.0 Support
Can you update it to new version?

### PR DESCRIPTION
**Pull request by n-o-o-n**

### CODE REVIEW

**Comment by tkmru** [comment]
Thanks @n-o-o-n ! I checked work of your pull request on IDA7. It's awesome.
but it can't eliminate deadcode. Can you fix?

**Comment by tkmru** [comment]
It can't eliminate deadcode in ```sample_bin/deadcode_sample2_pe32.exe```.
naobug

**Comment by n-o-o-n** [comment]
Fixed, please see [this commit](https://github.com/n-o-o-n/nao/commit/ffe708c4ec81ed584be29d09493a026e9097a666).
However, there is a problem that still remains. For any sufficiently non-trivial function, `emu.emu_start` will stop complaining about read or write to an unmapped memory. And this will result in skipping all processing.

**Comment by tkmru** [comment]
Thanks @n-o-o-n .  Awesome!! Now, nao work completely on IDA7, but test code failed. I will make new issue for this.

**Comment by tkmru** [comment]
[In unitetest, ImportError: No module named idaapi · Issue #40 · tkmru/nao](https://github.com/tkmru/nao/issues/40)

**Pull request merged**
